app = "api-rag"
primary_region = "mad"

[build]

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

[[vm]]
  memory_mb = 2048
  cpu_kind = "shared"
  cpus = 1

[experimental]
  kill_signal = "SIGINT"
  kill_timeout = "5s"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
